### ISSUE TITLE
Arrow function correction

### ISSUE THREAD

**Issue by Kodemon** [niftylettuce/frisbee#1]
When you define a arrow function within a class method you no longer have to resort to assigning the 'this' context to refer to the class.

Arrow methods use the direct parent context when referring to 'this'.

https://github.com/niftylettuce/frisbee/blob/master/src/frisbee.js#L57

Source: http://codepen.io/somethingkindawierd/post/es6-arrow-functions-this

When I first learned this, arrow methods become really exciting.

**Comment by niftylettuce** [comment]
thanks @Kodemon nice find
