### ISSUE TITLE
Breaking changes in v3

### ISSUE THREAD

**Issue by Almouro** [niftylettuce/frisbee#100]
Hi @niftylettuce!

From what I can see, some breaking changes were introduced in v3 but are not necessarily mentioned in v3:
- config changes (`arrayFormat` should now be in `stringify` object)
- query params are now parsed and encoded even if hardcoded in the url

Would it be possible to have a list of breaking changes introduced in v3?

**Comment by niftylettuce** [comment]
I am working on this now

**Comment by niftylettuce** [comment]
All changes are noted under Releases section <https://github.com/niftylettuce/frisbee/releases> here on GitHub
