### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by tonyxiao** [niftylettuce/frisbee#13]
How do you log request / response for debugging purposes with Frisbee?

**Comment by niftylettuce** [comment]
@tonyxiao nothing is built in right now, if you're on Node we could add `debug` package so you could run with `DEBUG=frisbee` environment flag, otherwise if on browser we'd have to put console logs or something, hmm...  Any ideas?  Pull request would be really welcomed!

**Comment by niftylettuce** [comment]
In v3.0.0 of Frisbee you can do `DEBUG=frisbee node app.js` as we have `debug` integrated

**Comment by niftylettuce** [comment]
Soon to be released

**Comment by niftylettuce** [comment]
v3.0.0 is released with the ability to do DEBUG=frisbee node app.js to output debug statements.

**Comment by niftylettuce** [comment]
:tada: v3.0.1 is released with support for a custom `logRequest` and `logResponse` option :tada:

Here's a quick example, but you can see the [Logging and Debugging](https://github.com/niftylettuce/frisbee#logging-and-debugging) section of the README for more insight.

```js
const cabin = require('cabin');
const frisbee = require('frisbee');
const pino = require('pino')({
  customLevels: {
    log: 30
  }
});

const logger = new Cabin({
  // (optional: your free API key from https://cabinjs.com)
  // key: 'YOUR-CABIN-API-KEY',
  axe: { logger: pino }
});

const api = new Frisbee({
  logRequest: (path, opts) => {
    logger.info('fetch request', { path, opts });
  },
  logResponse: res => {
    logger.info('fetch response', { res });
  }
});
```

Try it out and let me know if it works or if you need anything further:

```sh
npm install frisbee@latest
```

**Comment by niftylettuce** [comment]
Just an update - v3.0.2 now supports `logResponse` having three arguments, `path`, `opts`, and `response`.  It looks now like this:

```js
const api = new Frisbee({
  logRequest: (path, opts) => {
    logger.info('fetch request', { path, opts });
  },
  logResponse: (path, opts, res) => {
    logger.info('fetch response', { path, opts, res });
  }
});
```
