### ISSUE TITLE
Cannot set body of response which only has a getter

### ISSUE THREAD

**Issue by tonyxiao** [niftylettuce/frisbee#14]
Any ideas?
![image](https://cloud.githubusercontent.com/assets/696842/15636552/c50818dc-25b7-11e6-9090-0c459a0f4c3b.png)

**Comment by niftylettuce** [comment]
Can you provide example?

**Comment by tonyxiao** [comment]
Turns out that this error only happens when debugging in chrome with fetch polyfill turned off. 
```
// react-native/InitializeJavaScriptAppEngine.js
setUpErrorHandler();
// setUpXHR();
setUpGeolocation();
```

**Comment by tonyxiao** [comment]
i suppose it's not widely applicable then.

**Comment by niftylettuce** [comment]
I believe Frisbee does not work with Chrome at the moment - I will need to add cross-browser tests.  @tonyxiao might you be interested in adding this?  We could use SauceLabs, Browser Stack, Testling, or something else... hmm.

**Comment by niftylettuce** [comment]
frisbee should work in chrome afaik now, if any issues lmk
