### ISSUE TITLE
babel-runtime seems to be deprecated

### ISSUE THREAD

**Issue by tarikjn** [niftylettuce/frisbee#19]
It seems that `babel-runtime` is an undocumented package, the [official babel documentation](https://babeljs.io/docs/plugins/transform-regenerator/), suggest using either `babel-polyfill` (not a good idea for a lib) or Facebook's `regenerator-runtime/runtime`

On a higher level, I think Frisbee should not be using async/await and probably should stick to simple Promises. async/await are Promises behind the hood, and make it harder to reason about asynchronous execution flows, and you still end up having to interact with Promises for things such as `Promise.all`.

`async/await` were introduced to help expand Javascript to more programmers who are familiar with imperative programming and have a hard time breaking down nested calls, but generally should not be used by a library, especially when it introduces a runtime dependency.

**Comment by niftylettuce** [comment]
v2.x+ uses babel-preset-env and is compiled down to support node v6.4+ and major browsers via `.browserslistrc`.  there's also eslint browser compat testing built in now too.
