### ISSUE TITLE
Android Cookies are not persisted across network requests

### ISSUE THREAD

**Issue by udeesha** [niftylettuce/frisbee#26]
Hi,

When I am calling get its returning session expired. API is not getting cookie value along with get request. I can see the set-Cookie value in initial login(post) request. But its not using for next API calls. This is happening only in Android. iOS is working perfectly fine.

Any Idea what I am missing here.

**Comment by Steague** [comment]
This is happening to me as well on Android

**Comment by AhmedAliIbrahim** [comment]
any updates on this ?

**Comment by fdobre** [comment]
Hello, does this still happen in version 1.6.4?

**Comment by niftylettuce** [comment]
Doesn't work even with `credentials: 'include'` option?

**Comment by niftylettuce** [comment]
Closing, if this issue still persists let me know.
