### ISSUE TITLE
Abort() function

### ISSUE THREAD

**Issue by ACCTFORGH** [niftylettuce/frisbee#3]
Is abort() or similar function available? Fetch is known to not have abort() in place. I am considering to use frisbee in React Native but am thinking to cancel the connections when component unmounts. Or, could it be that, for fetch-based libraries, it is not necessary to have abort() function in place?

**Comment by niftylettuce** [comment]
@rmevans9 @ACCTFORGH can any of you make this PR to add this in?

**Comment by niftylettuce** [comment]
@ACCTFORGH I use it in React Native - it would be cool to have this abort() functionality when component unmounts!

**Comment by niftylettuce** [comment]
@ACCTFORGH see https://github.com/whatwg/fetch/issues/27

**Comment by ACCTFORGH** [comment]
@niftylettuce  Thanks!

**Comment by zsherman** [comment]
@niftylettuce seems like this landed in https://github.com/whatwg/fetch/pull/523

**Comment by Noitidart** [comment]
@niftylettuce may you please share how you do the abort in react-native, I am trying to do the same in RN.

**Comment by niftylettuce** [comment]
I've released v2.0.10 to NPM with support for this!

See https://github.com/niftylettuce/frisbee/pull/83#issuecomment-497967995
