### ISSUE TITLE
Credentials: 'same-origin' as options also?

### ISSUE THREAD

**Issue by 58a36f** [niftylettuce/frisbee#32]
Would it be possible to add credentials as option to Frisbee constructor?

Now I have to call it in every post request:

```
 api.post(
            '/api/bla',
            {
                body: {
                      text: "",
                      page: 0
                 },
                credentials: 'same-origin'
            }

```

**Comment by niftylettuce** [comment]
yeah u can pass it as an option, `opts.credentials` I think <https://github.com/crocodilejs/frisbee/blob/master/src/frisbee.js#L103>

lmk if that works

**Comment by niftylettuce** [comment]
You can pass `credentials: 'same-origin'` in your API requests since Frisbee passes `options` to the native Fetch implementation.

**Comment by niftylettuce** [comment]
v3.0.0 is released which fixes this issue 🎉 

`npm install frisbee@latest`
