### ISSUE TITLE
Authorization header should be customizable

### ISSUE THREAD

**Issue by jjhesk** [niftylettuce/frisbee#33]
@niftylettuce when after login  there is a token key dispatched from the server and it should be saved in the device. 
Can I use `auth('123123123ggg')` as the one string for future? Can i expect to see the header contains 
`Authorization: 123123123ggg` as the authorised token? Is  it a way to store this piece of string into frisbee for future header use?

**Comment by OmgImAlexis** [comment]
Also it'd be nice to have the option of authorisation header, custom header or even query string.

For example my application accept either a JWT in the authorisation header or `api_key=` in the url.

**Comment by niftylettuce** [comment]
Once you set `auth(str)` it saves it for the API for future requests.  If you call `auth()` again without a value it unsets it.  Similarly I believe `api.jwt()` or `api.jwt(null)` will also unset value.  See the docs API section for more info.   I think that `api_key=` in URL is non-standard.  But it could be added, you can simply set default query string parameters with your own custom logic.  PR is welcome if you want to add support for default query string parameters.  You can already set default headers.
