### ISSUE TITLE
are there any ways to turn off the cache

### ISSUE THREAD

**Issue by jjhesk** [niftylettuce/frisbee#34]
when i refresh the page the information response is still the old one.

**Comment by maikokuppe** [comment]
I took a look in the code and it seems that the `options` are passed to the native `fetch` implementation:
https://github.com/niftylettuce/frisbee/blob/master/src/frisbee.js#L184

According to the [https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch](Fetch API) you need add the `cache` key with value `reload` to the options:

```
res = await api.get('/v1/messages', { cache: 'reload' });
```

**Comment by OmgImAlexis** [comment]
@niftylettuce maybe add some docs showing that opts can be passed through to fetch?

**Comment by niftylettuce** [comment]
Done.
