### ISSUE TITLE
are there any interceptor on for the request call

### ISSUE THREAD

**Issue by jjhesk** [niftylettuce/frisbee#35]
as title

**Comment by Assem-Hafez** [comment]
Try https://github.com/Codelabsys/frisbee-intercept

**Comment by niftylettuce** [comment]
@Assem-Hafez any interest in adding this to frisbee itself?

**Comment by Assem-Hafez** [comment]
@niftylettuce sure, i think this is where it should be. i will send you a pull request ASAP (Y).

**Comment by niftylettuce** [comment]
Closed via https://github.com/niftylettuce/frisbee/issues/35.  Please install frisbee@1.6.0+.
