### ISSUE TITLE
Body parameters are empty in POST

### ISSUE THREAD

**Issue by calhouncole** [niftylettuce/frisbee#56]
Whenever making a POST request, the variables passed in body are empty. When passing the following to a POST endpoint, the result is {}

```
      const res = await api.post('/test', {
          body: {"test" : "test"}
        });
```

It works perfectly well with GET requests to GET endpoints.

**Comment by OmgImAlexis** [comment]
@calhouncole 
Would you mind please updating and just checking that you're still having the same issue with `v2.0.1`?

**Comment by niftylettuce** [comment]
Closing, if this issue still persists let me know.
