### ISSUE TITLE
Optional baseURI

### ISSUE THREAD

**Issue by bisubus** [niftylettuce/frisbee#58]
I was very enthusiastic about this package but had to switch back to Axios after figuring out that Frisbee is unable to do requests that are relative to current domain like `api.get('/api/endpoint')`.

Host environment variable isn't always available or practical. I would suggest to make it optional, as it is in every other library around.  If mandatory baseURI is there to address native platforms, this could be handled by platform detection.

**Comment by OmgImAlexis** [comment]
Could you not use `window.location` to set the baseURI dynamically? Or even set an interceptor to change it according to the current `window.location`?

**Comment by bisubus** [comment]
I likely can but I'm not sure why it should be done this way. 
location.origin isn't available in all browsers so base url should be constructed from location manually. It looks like unnecessary complication for a dev.

**Comment by niftylettuce** [comment]
yeah @bisubus we'll def fix this up.  give us a little bit

**Comment by niftylettuce** [comment]
done, please use v2.0.2+ - I've updated the README as well.

`npm install frisbee@latest` or `yarn add frisbee@latest`
