### ISSUE TITLE
param over url not working on v1.6.4

### ISSUE THREAD

**Issue by cms24us** [niftylettuce/frisbee#63]
as a exemple, i make GET over 'http://api.test.com/products/?name=&param1=&param2=false&param3=false&param4=false'

this kind of call works on version 1.6.0 but didn't work on version 1.6.4. 

it's giving me a authentication error (401). but the token is past correctly. 
i have no idea about what change between the two version but something go wrong.

**Comment by OmgImAlexis** [comment]
Could you please provide me with a reproducible code sample? I don't really have much to by with what you've provided so far.

Also would you mind please updating and just check that you're still having the same issue with `v2.0.1`.

**Comment by Bradzer** [comment]
Same here. 
Passing parameters over URL does not work on version 2.0.5.

Example: https://wordsapiv1.p.mashape.com/words?random=true

**Comment by ivkrpv** [comment]
confirm, still using 1.6.1 because of this issue

**Comment by niftylettuce** [comment]
v3.0.0 is released which fixes this issue 🎉 

`npm install frisbee@latest`
