### ISSUE TITLE
Integrate fetch-retry

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/frisbee#66]
https://github.com/jonbern/fetch-retry

**Comment by kasbah** [comment]
Could you explain why #73 amd #69 were linked here? They seem to be about setting a request timeout, a time period after which the request should be abandoned, like the `XMLHttpRequest` timeout. I don't think integrating a "retry" package will help with that.

**Comment by niftylettuce** [comment]
I think that `.retry` and `.timeout` options should be added together to be honest.

```js
(async () => {
  const frisbee = new Frisbee({
    // ...
    timeout: 10000, // 10 seconds
    retry: 0 // 0 = infinite retries
  });

  // could also use `.timeout` and `.retry` methods to set on a per-request basis
  const response = await frisbee.get('/').timeout(3000).retry(3);
}());
```

**Comment by niftylettuce** [comment]
Correct @kasbah, but in an ideal world we want to retry X number of times after Y number of timeout seconds per retry.

**Comment by niftylettuce** [comment]
cc @davidgovea

**Comment by niftylettuce** [comment]
Closing in favor of #92
