### ISSUE TITLE
Network Request Failed

### ISSUE THREAD

**Issue by ralfisalhon** [niftylettuce/frisbee#67]
Hello! I am trying to set up a phone verification using https://github.com/joinspontaneous/react-native-phone-verification

I am currently only using their example code, given here: https://github.com/joinspontaneous/react-native-phone-verification/blob/master/example/index.ios.js

However, I get this result when trying to run their code:
![simulator screen shot - iphone 8 - 2018-07-02 at 13 21 34](https://user-images.githubusercontent.com/16303372/42159006-f3eba6c6-7dfa-11e8-81e8-8dac66599e99.png)

Of course I have tried with my actual phone number, same result. I don't know how to approach this issue, and I am fairly new with React Native. Any help appreciated! Thanks! - Ralfi

**Comment by nccharles** [comment]
I have the same issue anyone to help

**Comment by juanjsebgarcia** [comment]
For anyone coming across this in the future. My issue was that I was using `localhost` on the device which does != `localhost` on the development PC. Once I used the IP of my development machine the error vanished.

**Comment by nccharles** [comment]
Please specify your own Bulk SMS URL fixed for me!
