### ISSUE TITLE
Logger hook

### ISSUE THREAD

**Issue by bugeats** [niftylettuce/frisbee#72]
Would be great to add some optional request logging with something like:

```javascript
new Frisbee({
  logger: myLogger
});
```

**Comment by niftylettuce** [comment]
In v3.0.0 of Frisbee you can do `DEBUG=frisbee node app.js` as we have debug integrated.  Soon to be released.

**Comment by niftylettuce** [comment]
v3.0.0 is released with the ability to do `DEBUG=frisbee node app.js` to output debug statements.

**Comment by bugeats** [comment]
Debug statements aren't the same as a logging hook, but ok.

**Comment by niftylettuce** [comment]
Ill add one in tonight for you

**Comment by niftylettuce** [comment]
:tada: v3.0.1 is released with support for a custom `logRequest` and `logResponse` option :tada:

Here's a quick example, but you can see the [Logging and Debugging](https://github.com/niftylettuce/frisbee#logging-and-debugging) section of the README for more insight.

```js
const cabin = require('cabin');
const frisbee = require('frisbee');
const pino = require('pino')({
  customLevels: {
    log: 30
  }
});

const logger = new Cabin({
  // (optional: your free API key from https://cabinjs.com)
  // key: 'YOUR-CABIN-API-KEY',
  axe: { logger: pino }
});

const api = new Frisbee({
  logRequest: (path, opts) => {
    logger.info('fetch request', { path, opts });
  },
  logResponse: res => {
    logger.info('fetch response', { res });
  }
});
```

Try it out and let me know if it works or if you need anything further:

```sh
npm install frisbee@latest
```

P.S. You are correct in that `xhook` does not work server-side, and I filed a GitHub issue here to track progress <https://github.com/jpillora/xhook/issues/103>.

**Comment by niftylettuce** [comment]
Just an update - v3.0.2 now supports `logResponse` having three arguments, `path`, `opts`, and `response`.  It looks now like this:

```js
const api = new Frisbee({
  logRequest: (path, opts) => {
    logger.info('fetch request', { path, opts });
  },
  logResponse: (path, opts, res) => {
    logger.info('fetch response', { path, opts, res });
  }
});
```

**Comment by bugeats** [comment]
Perfect! Nice work.

**Comment by niftylettuce** [comment]
@bugeats note that you can use interceptors to debug requests/responses easier - see the README for more insight/examples
