### ISSUE TITLE
Error / stack trace whenever API returns non-ok response

### ISSUE THREAD

**Issue by antgel** [niftylettuce/frisbee#85]
I'm using frisbee in an expo project, consuming a Python ([Flask-Classful](http://flask-classful.teracy.org/)) API. Whenever my API returns a non-`ok` response, I get a stack trace as follows:

```
Stack trace:
  node_modules/frisbee/lib/index.js:184:40 in _callee$
  node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:288:30 in invoke
  node_modules/frisbee/lib/index.js:7:103 in asyncGeneratorStep
  node_modules/frisbee/lib/index.js:9:212 in _next
  node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
  node_modules/promise/setimmediate/core.js:123:25 in <unknown>
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:14 in _callTimer
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:200:17 in _callImmediatesPass
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:464:30 in callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:320:6 in __callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in <unknown>
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 in flushedQueue
  ...
```

It's kind of difficult for me to debug, because my local `node_modules/frisbee/lib/index.js` is so different to the code in git, I believe due to regenerator. I'd be happy to learn how to debug this more smartly. I've read about babel and regenerator but as a newbie to this ecosystem it's a bit rough. I don't know if the issue is in frisbee or regenerator, and I don't understand why frisbee uses regenerator at all, as I don't see any `function*` in the code.

However, by judicious use of `console.log`, I understand that the problem occurs in `case 27:` in the transpiled code:

```
                  case 27:
                    resolve(res);
                    return _context.abrupt("return");
```

I believe that the original code is at https://github.com/niftylettuce/frisbee/blob/master/src/index.js#L210 (end of the `if (!res.ok)` block.

I hope this is enough information to understand what the issue is, but if not, I'm happy to provide more, just let me know what you need. I'm using Expo 32 and node 10.15.2.

**Comment by antgel** [comment]
After all that, this was my bad. It was caused by performing another API call from my app even though the previous one failed, was caught and the code should have stopped instead of attempting to continue as usual. I'm not sure if there is a genuine use case for this kind of behaviour, so closing and will reopen if necessary.

**Comment by niftylettuce** [comment]
@antgel note that you can use interceptors to debug requests/responses easier - see the README for more insight/examples
