### ISSUE TITLE
TypeScript definiton

### ISSUE THREAD

**Issue by The-Developeur** [niftylettuce/frisbee#87]
Hello,
Can you please add typescript definition to the librairie beacause your librairie is very nice for react-native and it has no equivalent.
Thank You !

**Comment by niftylettuce** [comment]
I do not support nor use TypeScript.  It is not pure JavaScript and it is not community-friendly for contributors.  Unfortunately I only use vanilla JavaScript across all of my projects to ensure the community can easily contribute.  Thank you though.

**Comment by cooolshekhar** [comment]
Can I please know the reason why typescript is not community-friendly for contributors?
