### ISSUE TITLE
.get() method strips trailing slash when GET params are passed in body

### ISSUE THREAD

**Issue by kz26** [niftylettuce/frisbee#88]
Affects latest version 2.0.6.

Basic example:
```
api = new Frisbee(...);
api.get('https://some-url.com/api/things/', {body: {param: something}});
```

On my test server, the request URL received is `https://some-url.com/api/things?param=something`, i.e. the trailing slash before the query string is missing. This isn't a big deal in most cases, but for web frameworks like Django that 301-redirect all URLs without trailing slashes, it adds an unnecessary redirect and extra HTTP request.

**Comment by davidgovea** [comment]
I'm seeing that behavior too. `fetch` leaves trailing slashes in place, so it makes sense to have frisbee match fetch's behavior.

Tried to write a quick test, but express (used for the test server) does not distinguish between `/route` and `/route/`, so a different approach will be needed. Perhaps spying on the calls to `fetch` to observe the processed URL.

Thanks for reporting!

**Comment by niftylettuce** [comment]
v3.0.0 is released which fixes this issue 🎉 

`npm install frisbee@latest`
