### ISSUE TITLE
api.auth API should accept a function instead of static singleton string 

### ISSUE THREAD

**Issue by gynet** [niftylettuce/frisbee#96]
Most web clients are getting jwt token strings from 3rd libs, so usually it returns from a sync/async/callback function. 
I think to make api.auth accepting a static token string shared by the entire lifecycle of the lib might not be a good idea. 

The client libraries written by other programming languages usually have a "TokenProvider" api which can accept a "function delegate" to support setup the header, it would be more flexible than a string.  It possible for firsebee to take a look?

**Comment by niftylettuce** [comment]
PR welcome
